pom.xml
#3 - The pom.xml file has been created in this pull request
=> Add pom.xml

README.md
General information concerning this module has been updated
=> Upd general info

src/main/java/com/artipie/gem/GemSlice.java, src/main/java/com/artipie/gem/package-info.java
`GemSlice` class has been created.
related to #3
=> add GemSlice

README.md
Add a useful link concerning ruby registry internals
=> Add a useful link 

src/main/java/com/artipie/gem/SubmitGem.java
Related to #3 
The Pull Request contains:
* placeholders for gem submission operation
* todo for subsequent implementation
=> Placeholders for submit operaition 

src/main/java/com/artipie/gem/GemInfo.java
The operation provides gem download url:
=> Placeholders for gem info operation

src/main/java/com/artipie/gem/GemInfo.java, src/main/java/com/artipie/gem/GemSlice.java
Parse gem name and response format(json or yml).
Related to #11
=> Parse gem info params

pom.xml, src/main/ruby/SubmitGem.rb, src/test/java/com/artipie/gem/SubmitGemITCase.java, src/test/java/com/artipie/gem/SubmitTest.java, src/test/java/com/artipie/gem/package-info.java
The PR includes:
* A java-based integration test for SubmitGem slice written in ruby
* SubmitGem slice java import improvement
Related to #13
=> A test for not-implemented Jruby slice

src/main/java/com/artipie/gem/GemSlice.java, src/main/ruby/SubmitGem.rb
Since SubmitGem need Storage access, we need to pass it via constructor
=> Pass Storage instance to SubmitGem slice

src/main/java/com/artipie/gem/ByteFlowIntoStringConversion.java, src/test/java/com/artipie/gem/ByteFlowIntoStringConversionTest.java
The conversion would be helpful in Jruby code for the stream to string conversion
=> Introduce ByteFlowIntoStringConversion

src/main/ruby/SubmitGem.rb
SubmitGem creates gem index dir when constructed
Depends on #18
=> Add separated dir for gem index

pom.xml, src/main/ruby/SubmitGem.rb, src/test/java/com/artipie/gem/SubmitGemITCase.java
This PR enables `SubmitGemITCase` and fixes the code, so the test passes.
=> Enable IT maven goal and fix SubmitGemITCase

src/main/ruby/SubmitGem.rb
Random name is generated using secure random and consisted of 32 random hex symbols postfixed with `.gem`
Closes #24
=> Random name for an uploaded gem

pom.xml, src/main/ruby/SubmitGem.rb
Update http dependency to 8.1 and remove intermediate conversion call.
=> Update http 7.1 -> 8.1

src/main/java/com/artipie/gem/GemSlice.java, src/test/java/com/artipie/gem/GemCliITCase.java
This pull request make gem adapter compatible with `gem install` command
Can be merged after #28.
=> Implement gem install with a test

.rultor.yml, ruby_lib.sh
=> Dont use rdoc

src/test/java/com/artipie/gem/SubmitGemITCase.java
'submitNotImplemented' does not represent what is actually happens with the test
=> Fix test name

pom.xml, src/main/java/com/artipie/gem/GemSlice.java, src/main/ruby/SubmitGem.rb, src/test/java/com/artipie/gem/GemCliITCase.java, src/test/java/com/artipie/gem/SubmitGemITCase.java
Now files are being synchronized after the index update
_Closes #30
_Closes #25
=> Sync local file with underlying storage

pom.xml, src/main/java/com/artipie/gem/GemSlice.java, src/main/ruby/SubmitGem.rb, src/test/java/com/artipie/gem/GemCliITCase.java, src/test/java/com/artipie/gem/SubmitGemITCase.java
=> Upgrade asto and http dependencies

src/main/java/com/artipie/gem/GemSlice.java, src/main/ruby/SubmitGem.rb, src/test/java/com/artipie/gem/GemCliITCase.java, src/test/java/com/artipie/gem/SubmitGemITCase.java
With this change, the gem module will work stable in artipie.
Related to #46
=> Remove fs param from slices and tests

src/main/ruby/SubmitGem.rb
In order to make gems available for download, we need to sync them with asto storage.
Related to #49.
=> Sync files from gems dir as well

pom.xml
=> Downgrade ppom version since a-central has corrupted jars

.rultor.yml
=> Add me as an arch

src/main/java/com/artipie/gem/GemApiKeyIdentities.java, src/main/java/com/artipie/gem/GemApiKeyIdentity.java, src/main/java/com/artipie/gem/GemSlice.java, src/test/java/com/artipie/gem/ApiKeyTest.java, src/test/java/com/artipie/gem/AuthTest.java, src/test/java/com/artipie/gem/GemCliITCase.java
=> Endpoint support auth with permissions

pom.xml, src/main/java/com/artipie/gem/GemApiKeyIdentities.java, src/main/java/com/artipie/gem/GemSlice.java, src/test/java/com/artipie/gem/AuthTest.java
Update http, asto and ppom and resolved all the problems.
=> Bumped http, asto and ppom

pom.xml, src/main/java/com/artipie/gem/ApiKeySlice.java, src/main/java/com/artipie/gem/GemApiKeyIdentities.java, src/test/java/com/artipie/gem/AuthTest.java
Updated `http` to `0.16.2` and `ppom` to `0.4.1`
=> Bumped http and ppom

pom.xml
=> Enable logs for tests

pom.xml, src/main/java/com/artipie/gem/ApiKeySlice.java, src/main/java/com/artipie/gem/GemApiKeyIdentities.java, src/main/java/com/artipie/gem/GemSlice.java, src/test/java/com/artipie/gem/AuthTest.java
Closes #81 
Support Basic authentication. Add test to verify it
=> #81 - Support Basic authentication

pom.xml
close #117 
Latest JRuby is supposed to fix known vulnerabilities
=> Upgrade JRuby to latest version

LICENSE.header, src/main/java/com/artipie/gem/GemIndex.java, src/main/java/com/artipie/gem/GemMeta.java, src/main/java/com/artipie/gem/UncheckedSupplier.java, src/main/java/com/artipie/gem/http/ApiGetSlice.java, src/main/java/com/artipie/gem/http/ApiKeySlice.java, src/main/java/com/artipie/gem/ruby/RubyGemIndex.java, src/main/java/com/artipie/gem/ruby/RubyGemMeta.java, src/main/java/com/artipie/gem/ruby/SharedRuntime.java, src/main/ruby/metarunner.rb
Added `RubyPlugin` interface to define objects which should be
initialized with Ruby runtime only once.
Refactored some HTTP `Slice`s.
=> refactoring: updated gem sdk, http layer

src/main/java/com/artipie/gem/Gem.java, src/main/java/com/artipie/gem/GemMeta.java
Removed temporary redundant atomic references,
fixed temp directory removing on future completion,
simplified move operation.
=> refactoring: refactored Gem SDK
